//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public Nullable<int> UserSendId { get; set; }
        public Nullable<int> UserReceiverId { get; set; }
        public string TextMessage { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual File File { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
