//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int ReplyId { get; set; }
        public Nullable<int> UserReplyId { get; set; }
        public Nullable<int> CommentReplyId { get; set; }
        public string TextContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
