//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Save
    {
        public int SaveId { get; set; }
        public Nullable<int> UserSaveId { get; set; }
        public Nullable<int> TargetSaveId { get; set; }
        public Nullable<int> TargetSaveType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CommentReplyId { get; set; }
    
        public virtual User User { get; set; }
    }
}
